version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-polymoney}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-polymoney}
      POSTGRES_DB: ${POSTGRES_DB:-polymoney}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:



